name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3

      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v10

      - name: Build website for production
        run: nix build .#for-production

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: result
          path: result/

  deploy-cf-workers:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Production
      url: https://intercollegiatemathtournament.org/
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: result
          path: result

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
