name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Nix
      - uses: DeterminateSystems/determinate-nix-action@v3

      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v7

      - name: Build website for production
        run: nix build .#for-production

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: result
          path: result/

  deploy-ocf:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Production
      url: https://intercollegiatemathtournament.org/
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: result

      - name: Deploy to OCF
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avPh --delete --exclude=.htaccess
          path: .
          remote_path: ~/public_html/
          remote_host: tsunami.ocf.berkeley.edu
          remote_user: icmt
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
